server:
  port: 9890
  servlet:
    context-path: /andun-pure

spring:
  datasource:
    #rm-2ze3zk2327k92186do.mysql.rds.aliyuncs.com
    #192.168.100.79
    url: jdbc:mysql://rm-2ze3zk2327k92186do.mysql.rds.aliyuncs.com:3306/andun_doctor?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&zeroDateTimeBeh avior=convertToNull&allowMultiQueries=true
    #java_xinrui xinrui1819
    #java_shouxing oVjR_gGlkNuAkeA5
    username: java_shouxing
    password: oVjR_gGlkNuAkeA5
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size:  15
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
  application:
    name: andun-pure
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
#  rabbitmq:
#    addresses: 127.0.0.1
#    username: andun_wxr
#    password: andun1819
#    port: 15672
#    virtual-host: /andun
#    #开启发送失败返回
#    publisher-returns: true
#    #开启发送确认
#    publisher-confirms: true
#    listener:
#      simple:
#        #指定最小的消费者数量.
#        concurrency: 2
#        #指定最大的消费者数量.
#        max-concurrency: 2
#        #开启ack
#        acknowledge-mode: manual
#        retry:
#          enabled: true
#          max-attempts: 3
#          initial-interval: 5000
#        default-requeue-rejected: false
#      #开启ack
#      direct:
#        acknowledge-mode: manual
#    #支持消息的确认与返回
#    template:
#      mandatory: true
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /
      listener:
        direct:
          acknowledge-mode: MANUAL
        simple:
          acknowledge-mode: MANUAL


mybatis:
  mapper-locations:
    - classpath:com/andun/platform/dao/impl/*.xml
  type-aliases-package: com.andun.model
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

mapper:
  identity: MYSQL
  not-empty: false

redis:
  database:
    fore: 0
    wechat: 1
  host: 192.168.100.28
  port: 6379
  timeout: 3000
  pool:
    max-idle: 30
    min-idle: 0
    max-wait: -1

shiro:
  token:
    key: helloworld
    expirate-time: 900
